# -*- coding: utf-8 -*-
"""Project 1 - PYBTCMP-1 / a2b2hny.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irsMfDZ91Ye1eJrycvf2zWsVKzcHSpBY

PROJECT I

TEAM: PYBTCMP-1

SUBTEAM: a2b2hny
"""

import pandas as pd
import numpy as np

class Student:
    def __init__(self, ad, soyad, okul_no, puan, harf_notu):
        self.ad = ad
        self.soyad = soyad
        self.okul_no = okul_no
        self.puan = puan
        self.harf_notu = harf_notu

def check_user_input(input):
    try:
      # Convert it into integer
      val = int(input)
      return 1
      print("Input is an integer number. Number = ", val)
    except ValueError:
        try:
          # Convert it into float
          val = float(input)
          return 2
          print("Input is a float  number. Number = ", val)
        except ValueError:
          return 0
          print("No.. input is not a number. It's a string")

dersler = ["Matematik", "Cebir", "Geometri", "Fizik", "Kimya"]
ders_secim = input(
    "Ders seçiniz:\n 1 - Matematik \n 2 - Cebir \n 3 - Geometri \n 4 - Fizik \n 5 - Kimya \n")

import sys
if not (int(ders_secim) >= 1 and int(ders_secim) <= 5):
    print("Ders seçimi için yanlış input girildi..")
    sys.exit()

ders_secim = int(ders_secim) - 1
print(dersler[ders_secim])
student_list = []

flag = True

while flag:
    print("Lütfen öğrenci bilgilerini yazınız. ")
    t_ad = input("Ad: ")
    ad_check = check_user_input(t_ad)
    while ad_check != 0:
      print("Ad yanlış girildi, tekrar deneyiniz. ")
      t_ad = input("Ad: ")
      ad_check = check_user_input(t_ad)

    t_soyad = input("Soyad: ")

    soyad_check = check_user_input(t_soyad)
    while soyad_check != 0:
      print("Soyad yanlış girildi, tekrar deneyiniz. ")
      t_soyad = input("Soyad: ")
      soyad_check = check_user_input(t_soyad)

    t_no = input("Okul No: ")
    
    t_puan = input("Puan: ")
    while (not(int(t_puan) <= 100 and int(t_puan) > 0)):
        print("Geçersiz puan inputu, tekrar deneyiniz. ")
        t_puan = input("Puan: ")

    t_harf_notu = -1
    if int(t_puan) >= 80:
        t_harf_notu = 'A'
    elif int(t_puan) >= 60:
        t_harf_notu = 'B'
    elif int(t_puan) >= 40:
        t_harf_notu = 'C'
    elif int(t_puan) >= 20:
        t_harf_notu = 'D'
    else:
        t_harf_notu = 'F'

    student_list.append(Student(t_ad, t_soyad, t_no, t_puan, t_harf_notu))
    tmp_checker = input(
        "Öğrenci bilgisi eklemeye devam etmek için 1, Çıkmak için 2 tuşuna basınız. ")
    tmp_checker = int(tmp_checker)
    if tmp_checker == 2:
        flag = False

gecti_kaldı = []
i = 0
for data in student_list:
    if int(data.puan) >= 50:
        gecti_kaldı.append("Geçti")
    else:
        gecti_kaldı.append("Kaldı")
    i = i + 1

adlar = []
soyadlar = []
puanlar = []
harf_notları = []

for data in student_list:
    adlar.append(data.ad)
    soyadlar.append(data.soyad)
    puanlar.append(data.puan)
    harf_notları.append(data.harf_notu)

dic = {'Ad': adlar, 'Soyad': soyadlar,
       'Puan': puanlar, 'Geçti/Kaldı': gecti_kaldı, 'Harf Notu': harf_notları}
df = pd.DataFrame(dic)
df

df.to_excel("Project 1_PYBTCMP-1/a2b2hny.xlsx")